apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
 #变成0就可以删除container 记得要变回1
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: lecture19-smoothie-stand-server
        name: server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: server
        env:
        - name: MONGO_URL
          value: mongodb://db:27017/easytask
